# Generated by Django 4.0.3 on 2022-04-06 10:26

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0004_alter_taggeditem_content_type_alter_taggeditem_tag'),
        ('shoppingList', '0003_alter_shoppinglist_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaggedShoppingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='shoppinglist',
            name='products',
            field=taggit.managers.TaggableManager(help_text='Type your comma-separated list of products', through='shoppingList.TaggedShoppingList', to='taggit.Tag', verbose_name='Products'),
        ),
        migrations.AddField(
            model_name='taggedshoppinglist',
            name='content_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoppingList.shoppinglist'),
        ),
        migrations.AddField(
            model_name='taggedshoppinglist',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='taggit.tag'),
        ),
    ]
