# Generated by Django 4.0.3 on 2022-04-04 09:28

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='esuser',
            name='profile_pic',
            field=models.ImageField(blank=True, default='/profiles/default_pic.png', upload_to=accounts.models.ESUser.user_directory_path),
        ),
    ]
